import React from "react";
import "../style/policy.scss";
import { Link } from "react-router";

const TermsOfService = () => {
    return (
        <div className="policy-page">
            <div className="policy-card">
                <Link to="/" className="back-btn">
                            ← Back to Home
                </Link>

                <h1 className="blue-title">📜 Terms of Service</h1>

                <p className="subtitle">
                    Please read these terms carefully before using our AI Interview Preparation platform.
                </p>

                <section>
                    <h2>✅ Acceptable Use</h2>
                    <ul>
                        <li>Use the platform for interview preparation purposes only.</li>
                        <li>Do not upload harmful, illegal, or copyrighted content.</li>
                        <li>Respect other users and applicable laws.</li>
                    </ul>
                </section>

                <section>
                    <h2>🤖 AI Generated Content</h2>
                    <p>
                        Interview plans, feedback, and recommendations are generated by AI.
                        They are intended to assist your preparation and should not be considered
                        professional career advice.
                    </p>
                </section>

                <section>
                    <h2>📁 User Responsibilities</h2>
                    <ul>
                        <li>You are responsible for the files and information you upload.</li>
                        <li>Ensure that uploaded resumes belong to you or you have permission to use them.</li>
                        <li>Do not attempt to misuse or disrupt the platform.</li>
                    </ul>
                </section>

                <section>
                    <h2>⚖️ Limitation of Liability</h2>
                    <p>
                        We strive to provide accurate AI-generated interview preparation,
                        but we cannot guarantee interview success or employment outcomes.
                    </p>
                </section>

                <div className="policy-footer">
                    Effective Date: July 2026
                </div>

            </div>
        </div>
    );
};

export default TermsOfService;